In [1]:
import pandas as pd
import numpy as np

In [13]:
df=pd.DataFrame({'seq':[10,30,np.nan],
             'name':['park','kim','choi'],
             'age':[25,35,22]})

In [14]:
df

seq  name  age
0  10.0  park   25
1  30.0   kim   35
2   NaN  choi   22

In [11]:
df.sort_values(by='seq',ascending=False,inplace=True) # inplace:df에 결과 저장

In [16]:
df.sort_values(by='seq')#,na_position='first')

seq  name  age
0  10.0  park   25
1  30.0   kim   35
2   NaN  choi   22

In [17]:
tup=[(1,'kim',25),(3,'lee',20),(2,'park',15)]

In [18]:
tup

[(1, 'kim', 25), (3, 'lee', 20), (2, 'park', 15)]

In [26]:
sorted(tup,key=lambda p:p[2],reverse=True)

[(1, 'kim', 25), (3, 'lee', 20), (2, 'park', 15)]

In [27]:
myList=[0,1,2,5,4,7,8,6,3]

In [32]:
sorted(myList)

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [29]:
myList.sort()

In [30]:
myList

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [33]:
s1=pd.Series([3,1,4,2,5])

In [38]:
s1[s1>s1.mean()]

2    4
4    5
dtype: int64

In [39]:
s1[[4,2]]

4    5
2    4
dtype: int64

In [40]:
s=pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])

In [42]:
s['a']

10

In [43]:
s.get(['a','c'])

a    10
c    30
dtype: int64

In [45]:
'a' in s

True

In [47]:
for i in s:
    print(i)

10
20
30
40
50


In [65]:
df=pd.DataFrame({
    'c1':[1,2,3],
    'c2':[4,5,6],
    'c3':[7,8,np.nan]
},index=['r1','r2','r3'],dtype=int)

In [66]:
df

c1  c2   c3
r1   1   4    7
r2   2   5    8
r3   3   6  NaN

In [59]:
df.index

Index(['r1', 'r2', 'r3'], dtype='object')

In [57]:
df.columns

Index(['c', 'c2', 'c3'], dtype='object')

In [69]:
df2=df.iloc[[0,2]]

In [70]:
df2

c1  c2   c3
r1   1   4    7
r3   3   6  NaN

In [71]:
df13=pd.DataFrame(df,index=['r1','r3'])

In [72]:
df13

c1  c2   c3
r1   1   4    7
r3   3   6  NaN

In [78]:
df

c1  c2   c3
r1   1   4    7
r2   2   5    8
r3   3   6  NaN

In [74]:
dfc13=pd.DataFrame(df,columns=['c1','c3'])

In [75]:
dfc13

c1   c3
r1   1    7
r2   2    8
r3   3  NaN

In [76]:
dfc13=df.iloc[:,[0,2]]

In [77]:
dfc13

c1   c3
r1   1    7
r2   2    8
r3   3  NaN

In [81]:
rfrc13=pd.DataFrame(df,index=['r3','r1'],columns=['c3','c1'])

In [82]:
rfrc13

c3  c1
r3  NaN   3
r1    7   1

In [83]:
rfrc13=df.iloc[[2,0],[2,0]]

In [84]:
rfrc13

c3  c1
r3  NaN   3
r1    7   1

In [85]:
df

c1  c2   c3
r1   1   4    7
r2   2   5    8
r3   3   6  NaN

In [86]:
df['c4']=df['c1']+df['c2']

In [87]:
df

c1  c2   c3  c4
r1   1   4    7   5
r2   2   5    8   7
r3   3   6  NaN   9

In [88]:
df.assign(c5=df['c1']*df['c2'])

c1  c2   c3  c4  c5
r1   1   4    7   5   4
r2   2   5    8   7  10
r3   3   6  NaN   9  18

In [95]:
df=df.assign(c6=lambda x:x.c1-x.c2) # x에는 df가 전달됨

In [96]:
df

c1  c2   c3  c4  c6
r1   1   4    7   5  -3
r2   2   5    8   7  -3
r3   3   6  NaN   9  -3

In [102]:
df

c1  c2   c3  c4  c6
r1   1   4    7   5  -3
r2   2   5    8   7  -3
r3   3   6  NaN   9  -3

In [98]:
df.drop(['c4','c2'],axis=1)

c1   c3  c6
r1   1    7  -3
r2   2    8  -3
r3   3  NaN  -3

In [100]:
df.drop(['r2'])

c1  c2   c3  c4  c6
r1   1   4    7   5  -3
r3   3   6  NaN   9  -3

In [101]:
df

c1  c2   c3  c4  c6
r1   1   4    7   5  -3
r2   2   5    8   7  -3
r3   3   6  NaN   9  -3

In [103]:
del df['c2'] # del은 열 데이터만 삭제 가능

In [105]:
df

c1   c3  c4  c6
r1   1    7   5  -3
r2   2    8   7  -3
r3   3  NaN   9  -3

In [106]:
df[df.c1<=2]

c1 c3  c4  c6
r1   1  7   5  -3
r2   2  8   7  -3

In [108]:
arr1=np.array([1,2,3,4])
myList=[5,6,7,8]
arr2=np.array(myList)

In [111]:
arr2

array([5, 6, 7, 8])

In [117]:
mylist=np.asarray(myList,dtype=float)

In [123]:
mylist[3]=np.inf

In [124]:
mylist

array([ 5.,  6.,  7., inf])

In [125]:
np.asarray_chkfinite(mylist)

ValueError: array must not contain infs or NaNs

In [129]:
np.ones([5,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [138]:
np.empty(10) # 출력되는 값은 임의의 값

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [145]:
arr=np.arange(12).reshape(3,4)

In [146]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
np.zeros_like(arr)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [144]:
np.ones_like(arr)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [149]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [148]:
np.identity(3) # eye와 큰 차이가 없어서 eye만 알아도 됨

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [154]:
np.random.normal(size=5)

array([ 0.32901976, -0.79776336, -0.18887942, -0.61149786,  0.88856422])

In [161]:
np.random.seed(777) # 시드 수가 같으면 동일한 난수 생성
np.random.normal(size=(2,5))

array([[-0.46820879, -0.82282485, -0.0653801 , -0.71336192,  0.90635089],
       [ 0.76623673,  0.82605407, -1.32368279, -1.75244452,  1.00244907]])

In [162]:
np.random.normal(size=(2,5))

array([[ 0.54480945,  1.8951609 , -0.76935745, -1.40309592, -0.63246751],
       [-0.55887367, -1.23323138, -0.43950352,  0.91478726,  0.26504093]])

In [163]:
np.random.binomial(n=1,p=0.5,size=20)

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0])

In [166]:
x=np.array([31,22,43,54])
x.dtype

dtype('int32')

In [168]:
x=np.array([3.1,2.5,4.2,5.4],dtype=np.float32)
x.dtype

dtype('float32')

In [169]:
x=np.array([3.1,2.5,4.2,5.4],dtype=np.int32)
x.dtype

dtype('int32')

In [170]:
x

array([3, 2, 4, 5])

In [171]:
np.int32([1.5,2.4])

array([1, 2])

In [172]:
x

array([3, 2, 4, 5])

In [175]:
x.astype(np.float64)

array([3., 2., 4., 5.])

In [176]:
x

array([3, 2, 4, 5])

In [179]:
x=np.float64([3,2,1])

In [180]:
x

array([3., 2., 1.])

In [182]:
np.int64(x)

array([3, 2, 1], dtype=int64)

In [184]:
x.astype(np.int64)

array([3, 2, 1], dtype=int64)

In [187]:
x=x.astype(np.string_)

In [189]:
x.dtype

dtype('S32')

In [191]:
x=np.array([1,1,2,2],dtype=np.float64)
y=np.array([1,1,2,2],dtype=np.float64)

In [193]:
y+1

array([2., 2., 3., 3.])

In [194]:
a=np.arange(1000000)

In [195]:
a

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [196]:
%timeit a+1 # %timeit 뒤에 오는 문장 실행에 걸리는 시간 측정

2.27 ms ± 26.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [197]:
%timeit [i+1 for i in a]

399 ms ± 8.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
